---
# This playbook deploys a new EC2 instance

- hosts: localhost
  connection: local
  gather_facts: False
  vars_prompt:
    - name: vpc_id
      prompt: VPC id
      private: no
      default: vpc-d8c0f4bc
    - name: subnet_id
      prompt: Subnet id
      private: no
      default: subnet-b68a16c0
  tasks:
    - name: Create EC2 Security Group
      ec2_group:
        name: ghuser-sg
        description: ghuser
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    - name: Create EC2 instance
      ec2:
        key_name: "{{ instance_name }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group: "default,ghuser-sg"
        image: ami-759bc50a # Ubuntu 16.04 hvm:ebs-ssd
        instance_type: t2.small
        wait: true
        instance_tags:
          Name: "{{ instance_name }}"
      register: created_instance
    - add_host:
        hostname: "{{ created_instance.instances[0].public_ip }}"
        groupname: created_instance
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ created_instance.instances[0].public_ip }}"
        port: 22

- hosts: created_instance
  gather_facts: True
  user: ubuntu
  vars_prompt:
    - name: git_name
      prompt: Git name
      private: no
      default: Aurelien Lourot
    - name: git_email
      prompt: Git email
      private: no
      default: aurelien.lourot@gmail.com
  tasks:
    - name: Download Node.js setup script
      get_url:
        url: https://deb.nodesource.com/setup_10.x
        dest: /tmp/
        mode: 0755
    - name: Run Node.js setup script
      command: /tmp/setup_10.x
      become: True
    - name: Install Node.js
      apt:
        name: nodejs
      become: True
    - name: Setup Git user name
      git_config:
        name: user.name
        scope: global
        value: "{{ git_name }}"
    - name: Setup Git user e-mail address
      git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"
    - name: git clone ghuser.io
      git:
        repo: https://github.com/AurelienLourot/ghuser.io.git
        dest: /home/ubuntu/ghuser.io/
    - name: npm install ghuser.io's DB
      command: npm install
      args:
        chdir: /home/ubuntu/ghuser.io/db/
    - name: Hint
      vars:
        msg: |
          EC2 instance ready. You can e.g. do:
          $ ssh -i secret.pem ubuntu@{{ inventory_hostname }}
          $ tmux new-session -s 0
          [C-b d]
          $ tmux attach -t 0
          $ cd ghuser.io/db/
          $ export GITHUB_CLIENT_ID=0123456789abcdef0123
          $ export GITHUB_CLIENT_SECRET=0123456789abcdef0123456789abcdef01234567
          $ export GITHUB_USERNAME=AurelienLourot
          $ export GITHUB_PASSWORD=********
          $ ./fetchAndCalculateAll.sh
      debug:
        msg: "{{ msg.split('\n') }}"
